### ISSUE TITLE
Too many open files problem

### ISSUE THREAD

**Issue by gerardo-junior** [ryotarai/mallet#13]
![image](https://user-images.githubusercontent.com/9096410/92480258-09929080-f1bb-11ea-8c73-766897fa0613.png)

chisel: 1.7.0-rc9
mallet: 0.0.4
Ubuntu: 20.04.1 LTS
iptables: v1.8.4 (legacy)

**Comment by ryotarai** [comment]
This shows some processes in your machine open too many files.
Is Mallet opening too many files? If so, it is a bug of Mallet and I'll investigate it.
(You can see opened files with `lsof` command)

Also, you can increase max number of open files with `ulimit`.
